# Reproducible local build defaults. The arXiv packaging smoke test uses
# latexmk -norc with equivalent explicit PDFLaTeX flags.
$pdf_mode = 1;
$bibtex_use = 2;
$max_repeat = 6;
$out_dir = 'build';
$aux_dir = 'build';

$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 %O %S';
$bibtex = 'bibtex %O %B';

@default_files = ('main.tex');
$clean_ext = 'bbl blg run.xml synctex.gz';
